# html lang
language: en

# main menu navigation
menu:

  Archives: /archives

# Miscelaneous
favicon: /favicon.png

# stylesheets loaded in the <head>
stylesheets:
- /css/pteris.css

# scripts loaded in the end of the body
scripts:
- /js/pteris.js

keywords: pteris

headerImageUrl: /images/tent.jpg

avatar: /images/avatar.jpg

title: Jonas

description: Pain is inevitable, suffering is optional.
